version: "3.7"
services:
  vit_mnist:
    image: vit:0.0.1
    build: .
    container_name: vit_mnist
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: root
    volumes:
      - ./weights:/app/weights
      - ./datasets:/app/datasets